version: '3.7'

services:
  mysql-prod:
    image: mysql:8.0.36-debian
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-network
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: waveTask_admin
      MYSQL_DATABASE: waveTask
      MYSQL_USER: waveTask_admin
      MYSQL_PASSWORD: waveTask_admin


  compilation:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    working_dir: /app
    volumes:
      - java-data:/app
      - ./pom.xml:/app/pom.xml
      - ./src:/app/src
    networks:
      - springboot-mysql-network
    command: mvn -Dmaven.test.skip=true -DskipTests=true clean install


  spring:
    image: openjdk:21-jdk
    ports:
      - "3050:3050"
    networks:
      - springboot-mysql-network
    links:
      - mysql-prod
    volumes:
      - java-data:/app
    environment:
      - spring.application.name=POEC_FIL_ROUGE_KAMBAN
      - server.port=3050
      - spring.datasource.url=jdbc:mysql://mysql-prod:3306/trello
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.username=trello_admin
      - spring.datasource.password=trello_admin
      - security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - security.jwt.expiration-time=3600000
      - spring.jpa.hibernate.ddl-auto=create-drop
    depends_on:
      compilation:
        condition: service_completed_successfully
    working_dir: /app
    command: ["java", "-jar", "./target/trello-0.0.1-SNAPSHOT.jar"]

  node:
    image: "node:18.20.2-slim"
    # environment:
    #   NODE_ENV: production
    volumes:
      - ./TaskWave/.:/app
      - /app/node_modules
    working_dir: /app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-network
    command: sh -c "npm install -g @angular/cli@17.3.2
      && npm install
      && npm run build
      && npm run deploy"
    depends_on:
      - spring
  
networks:
  springboot-mysql-network:

volumes:
  java-data: