version: '3'

services:
  # compilation:
  #   image: maven:latest
  #   volumes:
  #     - ./.:/app
  #   working_dir: /app
  #   command: mvn -Dmaven.test.skip=true -DskipTests=true clean install

  mysql:
    build:
      context: ./docker/
      dockerfile: base.dockerfile
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-network
    # depends_on:
    #   - compilation
    environment:
      MYSQL_ROOT_PASSWORD: trello_admin
      MYSQL_DATABASE: trello
      MYSQL_USER: trello_admin
      MYSQL_PASSWORD: trello_admin

  spring:
    build:
      context: ./
      dockerfile: java.dockerfile
    ports:
      - "3050:3050"
    networks:
      - springboot-mysql-network
    depends_on:
      - mysql

  # node:
  #   build:
  #     context: ./TaskWave/
  #     dockerfile: angular.dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - springboot-mysql-network
  #   depends_on:
  #     - spring
  
networks:
  springboot-mysql-network:
    name: springboot-mysql-network