version: '3'

services:
  mysql:
    image: mysql:8.0.36-debian
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-network
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: trello_admin
      MYSQL_DATABASE: trello
      MYSQL_USER: trello_admin
      MYSQL_PASSWORD: trello_admin


  compilation:
    image: maven:3.9.6-eclipse-temurin-21-alpine
    working_dir: /app
    volumes:
      - java-data:/app
      - ./pom.xml:/app/pom.xml
      - ./src:/app/src
    networks:
      - springboot-mysql-network
    command: mvn -Dmaven.test.skip=true -DskipTests=true clean install


  spring:
    image: openjdk:21-jdk
    ports:
      - "3050:3050"
    networks:
      - springboot-mysql-network
    links:
      - mysql
    volumes:
      - java-data:/app
    environment:
      - spring.application.name=WaveTask
      - server.port=3500
      - spring.datasource.url=jdbc:mysql://mysql-prod:3306/waveTask
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.username=waveTask_admin
      - spring.datasource.password=waveTask_admin
      - security.jwt.secret-key=CREATE_AND_USE_YOUR_OWN_SECRET_KEY
      - security.jwt.expiration-time=3600000
      - spring.jpa.hibernate.ddl-auto=create-drop
    depends_on:
      compilation:
        condition: service_completed_successfully
    working_dir: /app
    command: ["java", "-jar", "./target/trello-0.0.1-SNAPSHOT.jar"]
  
networks:
  springboot-mysql-network:

volumes:
  java-data: