version: '3'

services:
  compilation:
    image: maven:latest
    volumes:
      - ../.:/app
    working_dir: /app
    # command: mvn -Dmaven.test.skip=true -DskipTests=true clean install

  mysql:
    build:
      context: ./
      dockerfile: base.dockerfile
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-network
    environment:
      MYSQL_ROOT_PASSWORD: trello_admin
      MYSQL_DATABASE: trello
      MYSQL_USER: trello_admin
      MYSQL_PASSWORD: trello_admin

  spring:
    build:
      context: ../
      dockerfile: java.dockerfile
    ports:
      - "3050:3050"
    networks:
      - springboot-mysql-network
    depends_on:
      - mysql
      - compilation
    # environment:
      # SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/Trello
      # SPRING_DATASOURCE_USERNAME: trello_admin
      # SPRING_DATASOURCE_PASSWORD: trello_admin
      # SERVER_PORT: 3050
      # # SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      # ORG_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      # SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  node:
    build:
      context: ../TaskWave
      dockerfile: angular.dockerfile
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-network
    depends_on:
      - mysql
      - spring

# volumes:
#   maven-repo:
  
networks:
  springboot-mysql-network:
    name: springboot-mysql-network